name: Deprem Guncelleyici

on:
  schedule:
    - cron: '*/10 * * * *' # Her 10 dakikada bir çalış
  workflow_dispatch: # Manuel çalıştırma butonu

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
    - name: Depoyu Çek
      uses: actions/checkout@v3

    - name: Python Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Gerekli Paketleri Yükle
      run: pip install requests

    - name: Scripti Çalıştır
      run: python update_data.py

    - name: Değişiklikleri Kaydet ve Gönder
      run: |
        git config --global user.name 'DepremBotu'
        git config --global user.email 'bot@noreply.github.com'
        git add .
        # Eğer değişiklik varsa commit et, yoksa hata verme
        git diff --quiet && git diff --staged --quiet || (git commit -m "Otomatik güncelleme" && git push)
